### ISSUE TITLE
Design Custom Post (Single post) pages.

### ISSUE THREAD

**Issue by asayee0** [jefroy/wp-anime-review#24]
Once custom posts for anime are created (#2), site should be populated with 3-10 different anime posts

**Comment by matabeitt** [comment]
This is stored somewhere outside of the scope of .gitignore, further considerations should be made.

**Comment by shottah** [comment]
@jefroy make sure you have a wide scope so we can see
- [x] multiple genre per anime
- [x] multiple anime per genre
- [x] reviews

**Comment by shottah** [comment]
Also create custom content.
