### ISSUE TITLE
Home: Populate "Featured Posts" with Content.

### ISSUE THREAD

**Issue by shottah** [jefroy/wp-anime-review#33]
"Latest Post" should be changed to "Recent Anime" or "Latest Reviews" or "Genres".

It goes without saying that that module should be populated with only the relevant custom post type. I think it's best to only have this module only related to one custom post type. Who ever is doing this can go ahead and do it.

**Comment by shottah** [comment]
The featured banner does not show on all pages.

**Comment by asayee0** [comment]
> The featured banner does not show on all pages.

What pages specifically? Also what branch?

**Comment by shottah** [comment]
Should show on all front end pages. Home, single and archive pages.
