### ISSUE TITLE
Adjustments and fixes to archive.php

### ISSUE THREAD

**Issue by asayee0** [jefroy/wp-anime-review#62]
**This list will be broken up and moved soon to its respective branches** 

`archive.php` (accessible if you click on posts by adminuser for example)
- [x]  Change the title on the page to something more presentable
- [x]  Display the type of post (anime, or review) per post

`archive.php` (accessible if you click on posts by adminuser for example)
- [ ] Remove the empty genre box for post type: Review
- [ ] **FIX BUG**: clicking on any author shows all posts created by all authors, rather than just the one that was clicked

`front-page.php`
- [ ] Right sidebar should only show one tab (currently shows latest, popular, trending). The other tabs are pointless without the relevant functionalities.
- [ ] Right sidebar should show more info per anime
- [ ] ~~Should we remove the right sidebar below it (the one that starts with the search bar) its ugly af~~
- [x] Add a menu (#39) 

Pages
- [ ] Reviews (archive) page
- [ ] Show all anime (archive) page
- [ ] About page
- [ ] Sign up page

`anime-single.php`
- [ ] Center featured image (see One Piece for example; image is left justified)
- [ ] Show the original author of the post at top

Reviews section in `anime-single.php`
- [ ] Remove the word "random"
- [ ] Show reviewer name and date
- [ ] Show reviewer profile picture
- [ ] Implement "like" button functionality? (could take a while)

**Comment by shottah** [comment]
Consider redirecting these pages from `!is_admin()` to `front-page.php` or `/`:

- [ ] Author Page Template - This type of page is not used by our website and results in clutter if the user was to visit it.
- [ ] Page Template - Page post type is not used in the site and would just result in cluttered design if a user was to find it by accident.
- [ ] WP Signup Template - Now that I think about it, we want new users don't we?

**Comment by asayee0** [comment]
> Consider redirecting these pages from `!is_admin()` to `front-page.php` or `/`:
> 
> * [ ]  Author Page Template - This type of page is not used by our website and results in clutter if the user was to visit it.

How so? I was thinking that looking at the vanilla archive.php page is way messier.

> * [ ]  Page Template - Page post type is not used in the site and would just result in cluttered design if a user was to find it by accident.

I was able to make the change successfully without too much stress.

> * [ ]  WP Signup Template - Now that I think about it, we want new users don't we?

Oh yeah.. for sure we need to include this.

**Comment by shottah** [comment]
>How so? I was thinking that looking at the vanilla archive.php page is way messier.

Explain?
