### ISSUE TITLE
Create User Roles

### ISSUE THREAD

**Issue by asayee0** [jefroy/wp-anime-review#7]
- [x] 2 Types of Users
- [x]  User Permissions

**Comment by shottah** [comment]
1. `Authors` have the rights to create "Anime", "Genre".
2. `Editors` have the rights to create "Anime Reviews"

`User` is an implied role, which has read privileges on all content, and edit privileges only to comment on "Anime Reviews".

**Comment by asayee0** [comment]
Using https://wordpress.org/support/article/roles-and-capabilities/

**Comment by shottah** [comment]
We should implement this fully using the guidelines of `Week 12` lecture and lab content. Simply renaming the user roles is not enough in my head, and is not a suitable solution in the context of practicing the content.
