### ISSUE TITLE
Create a Live Search Across Entire Website (Cancelled)

### ISSUE THREAD

**Issue by asayee0** [jefroy/wp-anime-review#8]
See Lecture 10 for information on achieving this.

**Comment by jefroy** [comment]
hi good day

Lecture 10 was difficult for me, idk how to use gulp, and i never found the 4 gulp related files.

The search feature in the slides just covered up my site with an overaly XD, i dont think it worked

The built in search feature in the theme works pretty well, idk if yall modified it, but it searches for normal posts and custom posts and all pages.

what the built in search feature does NOT cover tho, is the 'live' part, im pretty sure by 'live', she means using AJAX to dynamically filter content on a page as we type it (like lecture 10)

> Live, working search across the content on the site

I think we could make a search feature that searches for post data per page similar to the built in search, but have it be dynamically updated live using ajax. that sounds kinda hard tho, and i rel dumb. we should prolly discuss this at some point idk

@matabeitt @asayee0

**Comment by asayee0** [comment]
Fixed #49
