### ISSUE TITLE
Ability for users to generate content

### ISSUE THREAD

**Issue by asayee0** [jefroy/wp-anime-review#9]
Must do #7 before this can be completed
Users with the appropriate role should be able to write create a post like a new anime, or a new review.

From the assignment doc: "Essential features include: - Allows user generated content"

**Comment by matabeitt** [comment]
Vague, could you explain?

**Comment by asayee0** [comment]
#7 Covers the assignment requirement.

For the "reviewers" role: Wordpress users with a valid account can make comments across all websites with a comment box. There is nothing to do here.
